import sgMail from '@sendgrid/mail'

/**
 * Sends a batch of personalized email notifications to users when a new signal is created.
 * @param {Object} signal - The newly created prisma signal object
 * @param {Array<Object>} recipients - Array of objects containing { email, firstName }
 */
export async function sendSignalEmail(signal, recipients) {
  const apiKey = process.env.SENDGRID_API_KEY
  const fromEmail = process.env.SENDGRID_FROM_EMAIL

  if (!apiKey || !fromEmail) {
    console.warn('[sendSignalEmail] SendGrid is not fully configured. Missing SENDGRID_API_KEY or SENDGRID_FROM_EMAIL in env.')
    return
  }

  sgMail.setApiKey(apiKey)

  if (!recipients || recipients.length === 0) {
    console.log('[sendSignalEmail] No eligible users to receive email notifications.')
    return
  }

  const messages = recipients.map(recipient => {
    const text = `Hi ${recipient.firstName || 'Trader'},\n\n` +
      `A new institutional-grade trading signal has been generated on the Antigravity Signal Platform!\n\n` +
      `Asset: ${signal.asset}\n` +
      `Action: ${signal.action}\n` +
      `Bias: ${signal.bias}\n` +
      `Entry Price: ${Number(signal.entryPrice)}\n` +
      `Take Profit: ${Number(signal.takeProfit)}\n` +
      `Stop Loss: ${Number(signal.stopLoss)}\n` +
      `Confidence: ${signal.confidencePct}%\n` +
      `Timeframe: ${signal.timeframe}\n` +
      `Timestamp: ${new Date(signal.createdAt).toUTCString()}\n` +
      `Model Version: ${signal.modelVersion}\n\n` +
      `Access the member dashboard to see full charts and detailed analytics: https://qauntumunstoppable.vercel.app\n\n` +
      `Disclaimer: Past performance is not indicative of future results. Trading involves risk of loss.\n\n` +
      `Best regards,\nAntigravity AI Engine Team`

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>⚡ New Signal Alert — ASP</title>
      </head>
      <body style="background-color: #080C12; color: #E2E8F0; font-family: 'Courier New', Courier, monospace; margin: 0; padding: 40px 10px;">
        <div style="background-color: #0D1B2A; border: 1px solid #0F2033; border-radius: 10px; padding: 32px 24px; max-width: 580px; margin: 0 auto; box-shadow: 0 4px 12px rgba(0,0,0,0.5);">
          <!-- Header -->
          <div style="text-align: center; border-bottom: 1px solid #0F2033; padding-bottom: 20px; margin-bottom: 24px;">
            <h2 style="color: #00B4D8; margin: 0; letter-spacing: 0.14em; font-size: 20px; font-weight: 700;">ANTIGRAVITY SIGNAL FEED</h2>
            <span style="font-size: 9px; color: #4A7C9E; letter-spacing: 0.1em; text-transform: uppercase;">MODEL ${signal.modelVersion} ACTIVE</span>
          </div>

          <!-- Body Content -->
          <p style="font-size: 13px; color: #A8C4D8; line-height: 1.7; margin-bottom: 16px;">Hi ${recipient.firstName || 'Trader'},</p>
          <p style="font-size: 13px; color: #A8C4D8; line-height: 1.7; margin-bottom: 24px;">A new high-conviction signal has been successfully generated by the AI Engine. Details below:</p>

          <!-- Signal Specs Card -->
          <div style="background-color: #080C12; border: 1px solid #0F2033; border-radius: 8px; padding: 20px; margin-bottom: 28px;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Asset</td>
                <td style="padding: 8px 0; font-size: 13px; color: #E2E8F0; font-weight: bold; text-align: right; border-bottom: 1px solid #0F203340;">${signal.asset}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Action</td>
                <td style="padding: 8px 0; font-size: 13px; color: ${signal.action === 'BUY' ? '#00D26A' : '#FF4D4D'}; font-weight: bold; text-align: right; border-bottom: 1px solid #0F203340;">
                  <span style="background-color: ${signal.action === 'BUY' ? 'rgba(0, 210, 106, 0.08)' : 'rgba(255, 77, 77, 0.08)'}; padding: 3px 10px; border-radius: 4px; border: 1px solid ${signal.action === 'BUY' ? 'rgba(0, 210, 106, 0.25)' : 'rgba(255, 77, 77, 0.25)'}; display: inline-block;">${signal.action}</span>
                </td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Bias</td>
                <td style="padding: 8px 0; font-size: 13px; color: #A8C4D8; text-align: right; border-bottom: 1px solid #0F203340;">${signal.bias}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Entry Price</td>
                <td style="padding: 8px 0; font-size: 13px; color: #E2E8F0; font-weight: bold; text-align: right; border-bottom: 1px solid #0F203340;">${Number(signal.entryPrice)}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Take Profit</td>
                <td style="padding: 8px 0; font-size: 13px; color: #00D26A; font-weight: bold; text-align: right; border-bottom: 1px solid #0F203340;">${Number(signal.takeProfit)}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Stop Loss</td>
                <td style="padding: 8px 0; font-size: 13px; color: #FF4D4D; font-weight: bold; text-align: right; border-bottom: 1px solid #0F203340;">${Number(signal.stopLoss)}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Confidence</td>
                <td style="padding: 8px 0; font-size: 13px; color: #00B4D8; font-weight: bold; text-align: right; border-bottom: 1px solid #0F203340;">
                  <span style="background-color: rgba(0, 180, 216, 0.08); padding: 3px 10px; border-radius: 4px; border: 1px solid rgba(0, 180, 216, 0.25); display: inline-block;">${signal.confidencePct}%</span>
                </td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid #0F203340;">Timeframe</td>
                <td style="padding: 8px 0; font-size: 13px; color: #A8C4D8; text-align: right; border-bottom: 1px solid #0F203340;">${signal.timeframe}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-size: 11px; color: #4A7C9E; text-transform: uppercase; letter-spacing: 0.08em;">Timestamp</td>
                <td style="padding: 8px 0; font-size: 13px; color: #A8C4D8; text-align: right;">${new Date(signal.createdAt).toUTCString()}</td>
              </tr>
            </table>
          </div>

          <!-- CTA Button -->
          <div style="text-align: center; margin-bottom: 32px;">
            <a href="https://qauntumunstoppable.vercel.app" style="background-color: #00B4D8; color: #000000; text-decoration: none; padding: 12px 28px; border-radius: 6px; font-weight: bold; font-size: 11px; letter-spacing: 0.1em; display: inline-block; text-transform: uppercase;">Access Dashboard</a>
          </div>

          <!-- Disclaimer -->
          <div style="border-top: 1px solid #0F2033; padding-top: 20px; font-size: 8px; color: #4A6880; line-height: 1.6; text-align: center;">
            Past performance is not indicative of future results. Trading involves significant risk of loss. Antigravity provides signal intelligence tools only and does not constitute financial or trade advice.
          </div>
        </div>
      </body>
      </html>
    `

    return {
      to: recipient.email,
      from: fromEmail,
      subject: `🚀 New Antigravity Signal: ${signal.asset} ${signal.action}`,
      text,
      html,
    }
  })

  try {
    await sgMail.send(messages)
    console.log(`[sendSignalEmail] Successfully dispatched ${messages.length} email notifications.`)
  } catch (err) {
    console.error('[sendSignalEmail] SendGrid API transaction failed:', err.response?.body || err.message)
  }
}
